version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  django:
    image: janni06/django-elternsprechtag:latest
    environment:
      - TZ=Europe/Berlin
      - DB_HOST=db
      - DB_NAME=elternsprechtagapp
      - DB_USERNAME=elternsprechtag
      - DB_PASSWORD=jhg2023
      - SECRET_KEY=supersecuresecretkey02
      - REDIS_HOST=redis
      - SUPER_USER_PASSWORD=test1234
      - SUPER_USER_EMAIL=test@test.com
      - DJANGO_SETTINGS_MODULE=elternsprechtag.settings.production
      - EMAIL_HOST=example.com
      - EMAIL_HOST_USER=example
      - EMAIL_HOST_PASSWORD=email
      - PUBLIC_URL=http://localhost:8080
      - EMAIL_COMPLETE=email@example.com
      - TZ=Europe/Berlin
      # optional for backup configuration
      # - USE_FTP_BACKUP=false
      # - FTP_SERVER=ftp.test.com
      # - FTP_USERNAME=test
      # - FTP_USER_PASSWORD=test1234
    volumes:
      - media:/app/media
      - static:/app/staticfiles
      - log:/var/log
    links:
      - redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: lscr.io/linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=jhg2023
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=elternsprechtagapp
      - MYSQL_USER=elternsprechtag
      - MYSQL_PASSWORD=jhg2023
    volumes:
      - db:/config
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  celery:
    image: janni06/django-elternsprechtag:latest
    command: celery -A elternsprechtag worker -B
    environment:
      - TZ=Europe/Berlin
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_NAME=elternsprechtagapp
      - DB_USERNAME=elternsprechtag
      - DB_PASSWORD=jhg2023
      - SECRET_KEY=supersecuresecretkey02
      - SUPER_USER_PASSWORD=test1234
      - SUPER_USER_EMAIL=test@test.com
      - EMAIL_HOST=example.com
      - EMAIL_HOST_USER=example
      - EMAIL_HOST_PASSWORD=email
      - PUBLIC_URL=http://localhost:8080
      - EMAIL_COMPLETE=email@example.com
      - TZ=Europe/Berlin
      # optional for backup configuration
      # - USE_FTP_BACKUP=true
      # - FTP_SERVER=ftp.test.com
      # - FTP_USERNAME=test
      # - FTP_USER_PASSWORD=test1234
    links:
      - redis
    volumes:
      - media:/app/media
      - static:/app/staticfiles
      - log:/var/log
    depends_on:
      - redis
      - django

  nginx:
    image: janni06/django-elternsprechtag-nginx:latest
    ports:
      - 8080:8080
    volumes:
      - static:/mnt/static:ro
      - media:/mnt/media:ro
    depends_on:
      - django

volumes:
  media:
  static:
  db:
  log:
