# Generated by Django 4.0.4 on 2022-05-16 13:19

import datetime
from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(default='hallo', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Upcomming_User',
            fields=[
                ('user_token', models.CharField(default=login.models.generate_unique_code, max_length=12, primary_key=True, serialize=False)),
                ('access_key', models.CharField(default=login.models.generate_unique_code, max_length=12)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
