# Generated by Django 4.0.4 on 2022-05-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='upcomming_user',
            name='child_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='upcomming_user',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
