# Generated by Django 4.0.4 on 2022-05-16 13:35

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_test_upcomming_user_child_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomming_user',
            name='otp',
            field=models.IntegerField(default=login.models.generate_unique_otp),
        ),
    ]
