# Generated by Django 4.0.4 on 2022-06-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_teacher',
        ),
    ]
