# Generated by Django 4.0.4 on 2022-05-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='child_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='upcomming_user',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.student'),
        ),
    ]
