# Generated by Django 4.0.4 on 2022-06-13 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_customuser_is_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomming_user',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upcomming_user',
            name='otp_verified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='upcomming_user',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
