# Generated by Django 4.0.4 on 2022-06-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_upcomming_user_otp_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomming_user',
            name='child_email',
        ),
    ]
