# Generated by Django 4.0.4 on 2022-08-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
