# Generated by Django 4.1 on 2022-08-26 21:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_sitesettings_event_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="time_end",
            field=models.TimeField(
                default=datetime.datetime(
                    2022, 8, 26, 21, 48, 43, 908262, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="time_start",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
