# Generated by Django 4.0.4 on 2022-08-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_event_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
