# Generated by Django 4.0.4 on 2022-08-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_event_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leed_days', models.IntegerField(default=7)),
                ('leed_inquiry_days', models.IntegerField(default=14)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
