# Generated by Django 4.1 on 2022-08-26 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_sitesettings_time_end_sitesettings_time_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="time_end",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
