# Generated by Django 4.0.4 on 2022-08-17 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='leed_days',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='leed_inquiry_days',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='leed_inquiry_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='leed_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
