# Generated by Django 4.1 on 2022-09-26 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0004_rename_parent_teacherstudentinquiry_respondent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherstudentinquiry",
            name="respondent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                limit_choices_to={"role": 0},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_respondent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
