# Generated by Django 4.1 on 2022-09-26 20:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_initial"),
        ("dashboard", "0005_alter_teacherstudentinquiry_respondent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeacherStudentInquiry",
            new_name="Inquiry",
        ),
    ]
