# Generated by Django 4.0.4 on 2022-08-22 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_teacherextradata_room'),
        ('dashboard', '0006_rename_leed_inquiry_start_sitesettings_lead_inquiry_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.student'),
        ),
    ]
