# Generated by Django 4.1 on 2022-09-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_inquiry_requester_alter_inquiry_respondent"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "Anfrage zur Buchung eines Termins (Lehrer->Eltern)"),
                    (1, "Anfrage zur Bestätigung eines Termins (Eltern->Lehrer)"),
                ],
                default=0,
            ),
        ),
    ]
