# Generated by Django 4.0.4 on 2022-08-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_teacherextradata_room'),
        ('dashboard', '0007_event_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='student',
        ),
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='authentication.student'),
        ),
    ]
