# Generated by Django 4.1 on 2022-09-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_inquiry_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiry",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
