# Generated by Django 4.1 on 2022-12-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_email_alter_customuser_first_name_and_more'),
        ('dashboard', '0009_inquiry_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='student',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='students',
            field=models.ManyToManyField(to='authentication.student'),
        ),
    ]
