# Generated by Django 4.1 on 2022-12-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_inquiry_student_inquiry_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unoccupied'), (1, 'Occupied'), (2, 'Inquiry pending')], default=0),
        ),
    ]
