# Generated by Django 4.1 on 2022-12-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_announcements_delete_announcments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='action_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='action_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
