# Generated by Django 4.1 on 2023-02-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_announcements_action_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='announcement_type',
            field=models.IntegerField(choices=[(0, 'Neue Buchungsanfrage'), (1, 'Termin absage'), (2, 'Systembenachrichtigung')], default=0),
        ),
    ]
