# Generated by Django 4.2 on 2023-09-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_sitesettings_impressum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='time_start',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='respondent_reaction',
            field=models.IntegerField(choices=[(0, 'Bisher keine Reaktion'), (1, 'Anfrage wurde angenommen'), (3, 'Anfrage wurde abgelehnt')], default=0),
        ),
    ]
