# Generated by Django 4.2 on 2023-10-14 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_announcements_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchangeformula',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 14, 20, 50, 30, 246243, tzinfo=datetime.timezone.utc)),
        ),
    ]
