# Generated by Django 4.2 on 2023-10-14 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_eventchangeformula_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventchangeformula',
            name='processed',
        ),
        migrations.AddField(
            model_name='eventchangeformula',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting to be filled'), (1, 'Waiting for approval'), (2, 'Approved'), (3, 'Disapproved')], default=0),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 14, 21, 8, 0, 442263, tzinfo=datetime.timezone.utc)),
        ),
    ]
