# Generated by Django 4.2 on 2023-10-14 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_eventchangeformula_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchangeformula',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 14, 22, 31, 6, 729112, tzinfo=datetime.timezone.utc), verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
