# Generated by Django 4.2 on 2023-10-15 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_eventchangeformula_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchangeformula',
            name='type',
            field=models.IntegerField(choices=[(0, 'Submit of personal timeslots')], default=0),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 15, 1, 12, 4, 143488, tzinfo=datetime.timezone.utc), verbose_name='Datum'),
        ),
    ]
