# Generated by Django 4.2 on 2023-10-24 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_eventchangeformula_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='announcement_type',
            field=models.IntegerField(choices=[(0, 'Neue Buchungsanfrage'), (1, 'Terminabsage'), (2, 'Systembenachrichtigung')], default=0),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 14, 36, 49, 855985, tzinfo=datetime.timezone.utc), verbose_name='Datum'),
        ),
    ]
