# Generated by Django 4.2 on 2023-10-24 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_announcements_announcement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchangeformula',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 24, 14, 36, 57, 436972, tzinfo=datetime.timezone.utc), verbose_name='Datum'),
        ),
    ]
