# Generated by Django 4.2 on 2023-10-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_eventchangeformula_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
