# Generated by Django 4.2 on 2024-01-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_announcements_options_alter_event_options_and_more'),
        ('dashboard', '0033_alter_announcements_options_alter_event_options_and_more'),
    ]

    operations = [
    ]
