# Generated by Django 4.2 on 2024-06-21 10:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0034_merge_20240109_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name': 'Mitteilung', 'verbose_name_plural': 'Mitteilungen'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Termin', 'verbose_name_plural': 'Termine'},
        ),
        migrations.AlterModelOptions(
            name='eventchangeformula',
            options={'verbose_name': 'Termin-Änderungsantrag', 'verbose_name_plural': 'Termin-Änderungsanträge'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Inquiry', 'verbose_name_plural': 'Anfragen'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Einstellungen', 'verbose_name_plural': 'Einstellungen'},
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'Frei'), (1, 'Belegt'), (2, 'Anfrage ausstehend')], default=0),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End Uhrzeit'),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='STart Uhrzeit'),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ausstehend'), (1, 'Warte auf Bestätigung'), (2, 'Bestätigt'), (3, 'Abgelehnt')], default=0),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Lehrer'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='respondent_reaction',
            field=models.IntegerField(choices=[(0, 'Keine Reaktion'), (1, 'Inquiry accepted'), (3, 'Inquiry dismissed')], default=0),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='event_duration',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Hier kann die Länge für alle Termine, die über die Funktion erstellt werden angegeben werden.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='lead_inquiry_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Hier kann festgelegt werden, ab wann Eltern, die eine Anfrage von einer Lehrkraft erhalten haben, einen Termin bei dieser buchen können.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='lead_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Hier kann festgelegt werden, ab wann alle Eltern Termine mit Lehrkräften vereinbaren können.'),
        ),
    ]
