# Generated by Django 4.2 on 2024-06-23 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_sitesettings_keep_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delete_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delete_events',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delete_student_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='keep_announcements',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
