# Generated by Django 4.2 on 2024-06-24 00:08

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_sitesettings_iquiry_bahvior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='iquiry_bahvior',
            field=models.JSONField(default=dashboard.models.SiteSettings.get_default_inquiry_behavior),
        ),
    ]
