# Generated by Django 4.2 on 2024-06-24 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_sitesettings_iquiry_bahvior'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delete_event_change_formulas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='keep_event_change_formulas',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
