# Generated by Django 5.0.6 on 2024-08-07 17:01

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_eventchangeformula_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('book_event', 'The user is allowed to book an event. Without this permission the user will be completely blocked from booking.'), ('inquiry_prebook_event', 'The user is allowed to book an event because an inquiry was issued to him.'), ('condition_prebook_event', 'The user is allowed to book an event before the official booking period because he has an e.g. medical condition.'), ('book_double_event', 'The user is allowed to book a double event with all teachers because of an medical condition.')], 'verbose_name': 'Termin', 'verbose_name_plural': 'Termine'},
        ),
        migrations.AddField(
            model_name='event',
            name='lead_allow_same_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='lead_end_timedelta',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='event',
            name='lead_inquiry_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Hier kann festgelegt werden, ab wann Eltern, die eine Anfrage von einer Lehrkraft erhalten haben, einen Termin bei dieser buchen können.'),
        ),
        migrations.AddField(
            model_name='event',
            name='lead_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Hier kann festgelegt werden, ab wann alle Eltern Termine mit Lehrkräften vereinbaren können.'),
        ),
    ]
