# Generated by Django 5.0.6 on 2024-08-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alter_event_options_event_lead_allow_same_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_allowed_parents',
            field=models.IntegerField(choices=[(0, 'No one is allowed to book this event'), (1, 'Only parents with special treatment are currently allowed to book this event.'), (2, 'All parents who received an inquiry from this teacher are allowed to book this event.'), (3, 'All parents are allowed to book this event.')], default=1),
        ),
    ]
