# Generated by Django 5.0.6 on 2024-08-07 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_event_booking_allowed_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_allowed_parents_last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
