# Generated by Django 5.0.6 on 2024-08-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_event_booking_allowed_parents_last_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='booking_allowed_parents',
            new_name='lead_status',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='booking_allowed_parents_last_change',
            new_name='lead_status_last_change',
        ),
    ]
