# Generated by Django 5.0.6 on 2024-08-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_rename_booking_allowed_parents_event_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lead_manual_override',
            field=models.BooleanField(default=False),
        ),
    ]
