# Generated by Django 5.0.6 on 2024-08-07 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_event_lead_manual_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='min_event_seperation',
            field=models.DurationField(default=datetime.timedelta(seconds=300), help_text='Here you can set the time between two events a parent can book. You should enter some time here to account for overtime and change of rooms.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='event_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=450), help_text='Hier kann die Länge für alle Termine, die über die Funktion erstellt werden angegeben werden.'),
        ),
    ]
