# Generated by Django 5.0.6 on 2024-08-07 22:42

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_sitesettings_min_event_seperation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('lead_start', models.DateField(default=django.utils.timezone.now, help_text='Hier kann festgelegt werden, ab wann alle Eltern Termine mit Lehrkräften vereinbaren können.')),
                ('lead_inquiry_start', models.DateField(default=django.utils.timezone.now, help_text='Hier kann festgelegt werden, ab wann Eltern, die eine Anfrage von einer Lehrkraft erhalten haben, einen Termin bei dieser buchen können.')),
                ('lead_end_timedelta', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('lead_allow_same_day', models.BooleanField(default=True)),
                ('lead_status', models.IntegerField(choices=[(0, 'No one is allowed to book this event'), (1, 'Only parents with special treatment are currently allowed to book this event.'), (2, 'All parents who received an inquiry from this teacher are allowed to book this event.'), (3, 'All parents are allowed to book this event.')], default=1)),
                ('lead_status_last_change', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead_manual_override', models.BooleanField(default=False)),
                ('room', models.CharField(blank=True, max_length=5, null=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='events_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.teachereventgroup'),
        ),
    ]
