# Generated by Django 5.0.6 on 2024-08-11 23:24

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0049_sitesettings_min_event_seperation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MainEventGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "lead_start",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Hier kann festgelegt werden, ab wann alle Eltern Termine mit Lehrkräften vereinbaren können.",
                    ),
                ),
                (
                    "lead_inquiry_start",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Hier kann festgelegt werden, ab wann Eltern, die eine Anfrage von einer Lehrkraft erhalten haben, einen Termin bei dieser buchen können.",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherEventGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lead_start",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Hier kann festgelegt werden, ab wann alle Eltern Termine mit Lehrkräften vereinbaren können.",
                    ),
                ),
                (
                    "lead_inquiry_start",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Hier kann festgelegt werden, ab wann Eltern, die eine Anfrage von einer Lehrkraft erhalten haben, einen Termin bei dieser buchen können.",
                    ),
                ),
                (
                    "lead_end_timedelta",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                ("lead_allow_same_day", models.BooleanField(default=True)),
                ("room", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "main_event_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.maineventgroup",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": 1},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="event_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.teachereventgroup",
            ),
        ),
    ]
