# Generated by Django 5.0.6 on 2024-08-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_maineventgroup_remove_event_lead_allow_same_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='lead_allow_same_day',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lead_end_timedelta',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lead_inquiry_start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='lead_start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='room',
        ),
    ]
