# Generated by Django 5.0.6 on 2024-08-11 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_remove_event_lead_allow_same_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='main_event_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.maineventgroup'),
        ),
    ]
