# Generated by Django 5.0.6 on 2024-08-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_event_main_event_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachereventgroup',
            name='lead_manual_override',
            field=models.BooleanField(default=False),
        ),
    ]
