# Generated by Django 5.0.6 on 2024-08-12 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_rename_event_group_event_teacher_event_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchangeformula',
            name='main_event_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.maineventgroup'),
        ),
        migrations.AddField(
            model_name='eventchangeformula',
            name='teacher_event_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.teachereventgroup'),
        ),
    ]
