# Generated by Django 5.0.6 on 2024-08-13 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_eventchangeformula_main_event_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_start', models.DateField(default=django.utils.timezone.now, help_text='Hier kann festgelegt werden, ab wann alle Eltern Termine mit Lehrkräften vereinbaren können.')),
                ('lead_inquiry_start', models.DateField(default=django.utils.timezone.now, help_text='Hier kann festgelegt werden, ab wann Eltern, die eine Anfrage von einer Lehrkraft erhalten haben, einen Termin bei dieser buchen können.')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='MainEventGroup',
            new_name='DayEventGroup',
        ),
    ]
