# Generated by Django 5.0.6 on 2024-08-13 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_baseeventgroup_rename_maineventgroup_dayeventgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayeventgroup',
            name='base_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.baseeventgroup'),
        ),
    ]
