# Generated by Django 5.0.6 on 2024-08-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_baseeventgroup_valid_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='main_event_group',
            new_name='day_group',
        ),
        migrations.RenameField(
            model_name='eventchangeformula',
            old_name='main_event_group',
            new_name='day_group',
        ),
        migrations.RenameField(
            model_name='teachereventgroup',
            old_name='main_event_group',
            new_name='day_group',
        ),
    ]
