# Generated by Django 5.0.6 on 2024-08-13 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_rename_main_event_group_event_day_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='base_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.baseeventgroup'),
        ),
    ]
