# Generated by Django 5.0.6 on 2024-08-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_baseeventgroup_force_baseeventgroup_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseeventgroup',
            name='manual_apply',
            field=models.BooleanField(default=False),
        ),
    ]
