# Generated by Django 5.0.6 on 2024-09-18 23:13

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_alter_announcements_options_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name': 'Benachrichtigung', 'verbose_name_plural': 'Benachrichtigungen'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('book_event', 'Dieser User darf kein Termin buchen. Ohne diese Berechtigung ist er komplett ausgeschlossen vom Buchen von Terminen.'), ('inquiry_prebook_event', 'Dieser User darf einen Termin anfragen, da er eine Anfrage einer Lehrkraft bekommen hat.'), ('condition_prebook_event', 'Dieser User darf aus z.B. medizinischen Gründen einen Termin vor der offiziellen Buchungsphasen anfragen.'), ('book_double_event', 'Dieser User darf aus z.B. medizinischen Gründen auch Doppeltermine bei einer Lehrkraft anfragen.')], 'verbose_name': 'Termin', 'verbose_name_plural': 'Termine'},
        ),
        migrations.AlterModelOptions(
            name='eventchangeformula',
            options={'permissions': [('approve_disapprove', 'Kann eingereichte Zeiträume für andere User annehmen oder ablehnen.')], 'verbose_name': 'Terminerstellungsformular', 'verbose_name_plural': 'Terminerstellungsformulare'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name': 'Anfrage', 'verbose_name_plural': 'Anfragen'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Seiteneinstellungen', 'verbose_name_plural': 'Seiteneinstellungen'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='event_in_seperation_bookable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baseeventgroup',
            name='lead_inquiry_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Setzen Sie fest, ab wann Anfragen der Lehrkräfte beantwortet werden können.'),
        ),
        migrations.AlterField(
            model_name='baseeventgroup',
            name='lead_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Setzen Sie fest, ab wann alle Eltern Termine anfragen können.'),
        ),
        migrations.AlterField(
            model_name='baseeventgroup',
            name='lead_status',
            field=models.IntegerField(choices=[(0, 'Niemand kann diesen Termin aktuell anfragen.'), (1, 'Nur Eltern mit besonderen Berechtigungen können diesen Termin aktuell anfragen.'), (2, 'Nur Eltern, die eine Anfrage der Lehrkraft bekommen haben, können diesen Termin aktuell anfragen.'), (3, 'Alle Eltern können diesen Termin aktuell anfragen.')], default=1),
        ),
        migrations.AlterField(
            model_name='dayeventgroup',
            name='lead_inquiry_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Setzen Sie fest, ab wann Anfragen der Lehrkräfte beantwortet werden können.'),
        ),
        migrations.AlterField(
            model_name='dayeventgroup',
            name='lead_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Setzen Sie fest, ab wann alle Eltern Termine anfragen können.'),
        ),
        migrations.AlterField(
            model_name='dayeventgroup',
            name='lead_status',
            field=models.IntegerField(choices=[(0, 'Nobody can currently request this appointment.'), (1, 'Only parents with special authorisations can currently request this appointment.'), (2, 'Only parents who have received a request from the teacher can currently request this appointment.'), (3, 'All parents can request this appointment at the moment.')], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='lead_status',
            field=models.IntegerField(choices=[(0, 'Nobody can currently request this appointment.'), (1, 'Nur Eltern mit besonderen Berechtigungen können diesen Termin aktuell anfragen.'), (2, 'Nur Eltern, die eine Anfrage der Lehrkraft bekommen haben, können diesen Termin aktuell anfragen.'), (3, 'Alle Eltern können diesen Termin aktuell anfragen.')], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'Frei'), (1, 'Belegt'), (2, 'Anfrage ausstehend')], default=0),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Endzeitpunkt'),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='no_events',
            field=models.BooleanField(default=False, verbose_name='Keine Termine'),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Startzeitpunkt'),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='status',
            field=models.IntegerField(choices=[(0, 'Warte auf Bearbeitung'), (1, 'Warte auf Bestätigung'), (2, 'Angenommen'), (3, 'Abgelehnt')], default=0),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Lehrkraft'),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='type',
            field=models.IntegerField(choices=[(0, 'Eigene Zeiträume abschicken.')], default=0),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='respondent_reaction',
            field=models.IntegerField(choices=[(0, 'Keine Antwort'), (1, 'Anfrage angenommen'), (3, 'Anfrage abgelehnt')], default=0),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='event_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=450), help_text='Hier legen Sie die allgemeine Länge eines Termins fest. Sie bezieht sich auf alle mit dieser Funktion erstellten Termine.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='lead_inquiry_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Setzen Sie fest, ab wann Anfragen der Lehrkräfte beantwortet werden können.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='lead_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Setzen Sie fest, ab wann alle Eltern Termine anfragen können.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='min_event_seperation',
            field=models.DurationField(default=datetime.timedelta(seconds=300), help_text='Hier können Sie den Abstand zwischen zwei Terminen festlegen. Sie sollten etwas Zeit zum Wechseln der Räume usw. einplanen.'),
        ),
        migrations.AlterField(
            model_name='teachereventgroup',
            name='lead_inquiry_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Setzen Sie fest, ab wann Anfragen der Lehrkräfte beantwortet werden können.'),
        ),
        migrations.AlterField(
            model_name='teachereventgroup',
            name='lead_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='Setzen Sie fest, ab wann alle Eltern Termine anfragen können.'),
        ),
        migrations.AlterField(
            model_name='teachereventgroup',
            name='lead_status',
            field=models.IntegerField(choices=[(0, 'Nobody can currently request this appointment.'), (1, 'Only parents with special authorisations can currently request this appointment.'), (2, 'Only parents who have received a request from the teacher can currently request this appointment.'), (3, 'All parents can request this appointment at the moment.')], default=1),
        ),
    ]
