# Generated by Django 5.0.6 on 2024-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_alter_event_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseeventgroup',
            name='lead_status',
            field=models.IntegerField(choices=[(0, 'Nobody can currently request this appointment.'), (1, 'Nur Eltern mit besonderen Berechtigungen können diesen Termin aktuell anfragen.'), (2, 'Nur Eltern, die eine Anfrage der Lehrkraft bekommen haben, können diesen Termin aktuell anfragen.'), (3, 'Alle Eltern können diesen Termin aktuell anfragen.')], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='lead_status',
            field=models.IntegerField(choices=[(0, 'Nobody can currently request this appointment.'), (1, 'Nur Eltern mit besonderen Berechtigungen können diesen Termin aktuell anfragen.'), (2, 'Nur Eltern, die eine Anfrage der Lehrkraft bekommen haben, können diesen Termin aktuell anfragen.'), (3, 'Alle Eltern können diesen Termin aktuell anfragen.')], default=1),
        ),
    ]
