# Generated by Django 5.0.6 on 2024-09-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_alter_baseeventgroup_lead_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('book_event', 'Dieser Nutzer darf Termin buchen. Ohne diese Berechtigung ist er komplett ausgeschlossen vom Buchen von Terminen.'), ('condition_prebook_event', 'Dieser Nutzer darf aus z.B. medizinischen Gründen einen Termin vor der offiziellen Buchungsphasen anfragen.'), ('book_double_event', 'Dieser Nutzer darf aus z.B. medizinischen Gründen auch Doppeltermine bei einer Lehrkraft anfragen.')], 'verbose_name': 'Termin', 'verbose_name_plural': 'Termine'},
        ),
        migrations.AlterField(
            model_name='baseeventgroup',
            name='lead_status',
            field=models.IntegerField(choices=[(0, 'Niemand kann diesen Termin aktuell anfragen.'), (1, 'Nur Eltern mit besonderen Berechtigungen können diesen Termin aktuell anfragen.'), (2, 'Nur Eltern, die eine Anfrage der Lehrkraft bekommen haben, können diesen Termin aktuell anfragen.'), (3, 'Alle Eltern können diesen Termin aktuell anfragen.')], default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='lead_status',
            field=models.IntegerField(choices=[(0, 'Niemand kann diesen Termin aktuell anfragen.'), (1, 'Nur Eltern mit besonderen Berechtigungen können diesen Termin aktuell anfragen.'), (2, 'Nur Eltern, die eine Anfrage der Lehrkraft bekommen haben, können diesen Termin aktuell anfragen.'), (3, 'Alle Eltern können diesen Termin aktuell anfragen.')], default=1),
        ),
    ]
