# Generated by Django 5.0.6 on 2024-09-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_alter_event_options_alter_baseeventgroup_lead_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('book_event', 'The user is allowed to book an event. Without this permission the user will be completely blocked from booking.'), ('condition_prebook_event', 'The user is allowed to book an event before the official booking period because he has an e.g. medical condition.'), ('book_double_event', 'The user is allowed to book a double event with all teachers because of an medical condition.')], 'verbose_name': 'Termin', 'verbose_name_plural': 'Termine'},
        ),
    ]
