# Generated by Django 5.0.6 on 2024-09-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('book_event', 'Dieser Nutzer darf Termin buchen. Ohne diese Berechtigung ist er komplett ausgeschlossen vom Buchen von Terminen.'), ('condition_prebook_event', 'Dieser Nutzer darf aus z.B. medizinischen Gründen einen Termin vor der offiziellen Buchungsphasen anfragen.'), ('book_double_event', 'Dieser Nutzer darf aus z.B. medizinischen Gründen auch Doppeltermine bei einer Lehrkraft anfragen.')], 'verbose_name': 'Termin', 'verbose_name_plural': 'Termine'},
        ),
    ]
