# Generated by Django 5.0.6 on 2024-09-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_alter_dayeventgroup_lead_status_and_more'),
        ('dashboard', '0072_alter_event_options'),
    ]

    operations = [
    ]
