# Generated by Django 5.0.6 on 2024-09-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_merge_20240926_2139'),
        ('dashboard', '0073_merge_20240926_2149'),
    ]

    operations = [
    ]
