# Generated by Django 5.0.6 on 2024-09-27 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_merge_20240926_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='base_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.baseeventgroup'),
        ),
    ]
