# Generated by Django 5.0.6 on 2024-10-04 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_event_base_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventchangeformula',
            name='parent_formular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childformular', to='dashboard.eventchangeformula'),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='type',
            field=models.IntegerField(choices=[(0, 'Eigene Zeiträume abschicken.'), (1, 'Request of break times')], default=0),
        ),
    ]
