# Generated by Django 5.0.6 on 2024-10-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_eventchangeformula_parent_formular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchangeformula',
            name='type',
            field=models.IntegerField(choices=[(0, 'Eigene Zeiträume abschicken.'), (1, 'Request of break times.'), (2, 'Request approval for illness')], default=0),
        ),
    ]
