# Generated by Django 5.0.6 on 2024-10-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_alter_eventchangeformula_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventchangeformula',
            name='status',
            field=models.IntegerField(choices=[(0, 'Warte auf Bearbeitung'), (1, 'Warte auf Bestätigung'), (2, 'Angenommen'), (3, 'Abgelehnt'), (4, 'Removed')], default=0),
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='type',
            field=models.IntegerField(choices=[(0, 'Zeitfenster'), (1, 'Pausenantrag'), (2, 'Krankschreibung')], default=0),
        ),
    ]
