# Generated by Django 5.0.6 on 2024-10-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_alter_eventchangeformula_type'),
        ('dashboard', '0079_eventchangeformula_created_at'),
    ]

    operations = [
    ]
