# Generated by Django 5.1.1 on 2024-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_alter_eventchangeformula_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventchangeformula',
            name='parent_formular',
        ),
        migrations.AlterField(
            model_name='eventchangeformula',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
