# Generated by Django 4.1 on 2022-09-27 21:16

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("synonymes", models.TextField(blank=True, null=True)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FA3651", image_field=None, max_length=18, samples=None
                    ),
                ),
            ],
        ),
    ]
