# Generated by Django 4.1 on 2022-08-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherextradata",
            name="acronym",
            field=models.CharField(default="", max_length=3),
        ),
    ]
