# Generated by Django 4.1 on 2022-08-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_teacherextradata_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_name",
            field=models.CharField(default="", max_length=2),
        ),
    ]
