# Generated by Django 4.0.4 on 2022-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_teacherextradata'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextradata',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
