# Generated by Django 4.1 on 2022-09-27 21:23

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_tag_delete_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#4F723A", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.RemoveField(
            model_name="teacherextradata",
            name="tags",
        ),
        migrations.AddField(
            model_name="teacherextradata",
            name="tags",
            field=models.ManyToManyField(blank=True, to="authentication.tag"),
        ),
    ]
