# Generated by Django 4.1 on 2022-09-27 21:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0005_alter_tag_color_remove_teacherextradata_tags_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="synonymes",
            new_name="synonyms",
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#1E6D58", image_field=None, max_length=18, samples=None
            ),
        ),
    ]
