# Generated by Django 4.1 on 2022-10-01 22:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_rename_synonymes_tag_synonyms_alter_tag_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherextradata",
            name="image",
            field=models.ImageField(blank=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#E21085", image_field=None, max_length=18, samples=None
            ),
        ),
    ]
