# Generated by Django 4.2 on 2023-11-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_student_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomming_user',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='upcomming_user',
            name='parent_registration_email_send',
            field=models.BooleanField(default=False),
        ),
    ]
