# Generated by Django 4.0.4 on 2022-09-29 20:48

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#C6DCA5', image_field=None, max_length=18, samples=None),
        ),
    ]
