# Generated by Django 4.0.4 on 2022-10-04 09:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#787C9D', image_field=None, max_length=18, samples=None),
        ),
    ]
