# Generated by Django 4.2 on 2023-12-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_upcomming_user_parent_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomming_user',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
