# Generated by Django 4.2 on 2023-12-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_options_alter_student_options_and_more'),
        ('authentication', '0009_alter_upcomming_user_parent_email'),
    ]

    operations = [
    ]
