# Generated by Django 4.1 on 2022-10-02 08:52

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_alter_tag_color_alter_teacherextradata_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#52FB1C", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="teacherextradata",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="teacher_pics/"),
        ),
    ]
