# Generated by Django 4.2 on 2024-01-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_options_alter_student_options_and_more'),
        ('authentication', '0010_merge_20231205_1119'),
    ]

    operations = [
    ]
