# Generated by Django 4.1 on 2022-10-02 08:53

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_alter_tag_color_alter_teacherextradata_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#A886F6", image_field=None, max_length=18, samples=None
            ),
        ),
    ]
