# Generated by Django 4.2 on 2024-06-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_customuser_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchange',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student', verbose_name=''),
        ),
    ]
