# Generated by Django 4.1 on 2022-10-04 12:55

import authentication.models
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_alter_tag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#8FAA7A", image_field=None, max_length=18, samples=None
            ),
        ),
        migrations.AlterField(
            model_name="upcomming_user",
            name="otp",
            field=models.CharField(
                default=authentication.models.generate_unique_otp, max_length=6
            ),
        ),
    ]
