# Generated by Django 4.1 on 2022-10-04 12:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_alter_tag_color_alter_upcomming_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                default="#3C0930", image_field=None, max_length=18, samples=None
            ),
        ),
    ]
