# Generated by Django 4.2 on 2024-06-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_studentchange_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchange',
            name='child_email',
            field=models.EmailField(max_length=200, null=True, verbose_name='Email des Kindes'),
        ),
        migrations.AddField(
            model_name='studentchange',
            name='class_name',
            field=models.CharField(max_length=4, null=True, verbose_name='Klassenname'),
        ),
        migrations.AddField(
            model_name='studentchange',
            name='first_name',
            field=models.CharField(max_length=48, null=True, verbose_name='Vorname'),
        ),
        migrations.AddField(
            model_name='studentchange',
            name='last_name',
            field=models.CharField(max_length=48, null=True, verbose_name='Nachname'),
        ),
    ]
