# Generated by Django 4.2 on 2024-06-21 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_studentchange_child_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchange',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
