# Generated by Django 4.2 on 2024-06-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_studentchange_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchange',
            name='shield_id',
            field=models.CharField(max_length=38, null=True, unique=True),
        ),
    ]
