# Generated by Django 4.2 on 2024-06-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_studentchange_shield_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchange',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentchange',
            name='operation',
            field=models.IntegerField(choices=[(0, 'no changes'), (1, 'Create new Student'), (2, 'Field Changes'), (3, 'Delete Student')], default=0),
        ),
    ]
