# Generated by Django 4.2 on 2024-06-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_studentchange_approved_alter_studentchange_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchange',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentchange',
            name='applied_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
