# Generated by Django 4.2 on 2024-06-21 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_studentchange_shield_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchange',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.student', verbose_name='Student'),
        ),
    ]
