# Generated by Django 4.2 on 2024-06-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_studentchange_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentchange',
            name='shield_id',
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
    ]
