# Generated by Django 4.2 on 2024-07-06 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_studentchange_shield_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentchange',
            options={'permissions': [('apply_changes', 'Can apply changes to the students')]},
        ),
    ]
