# Generated by Django 5.0.6 on 2024-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_alter_studentchange_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentchange',
            options={'permissions': [('apply_changes', 'Can apply changes to the students')]},
        ),
        migrations.AlterField(
            model_name='teacherextradata',
            name='acronym',
            field=models.CharField(default='', max_length=3, verbose_name='Abkürzung'),
        ),
    ]
