# Generated by Django 5.0.6 on 2024-10-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_alter_studentchange_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Benutzer*innen', 'verbose_name_plural': 'Benutzer'},
        ),
        migrations.AlterModelOptions(
            name='upcomming_user',
            options={'permissions': (('send_up_user', 'Can send upcomming user'), ('send_up_user_batch', 'Can batch send upcomming user')), 'verbose_name': 'Zukünftiger User', 'verbose_name_plural': 'Zukünftige User'},
        ),
    ]
