# Generated by Django 5.0.6 on 2024-08-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup', models.TextField()),
                ('params', models.TextField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('dump_version', models.TextField(blank=True, null=True)),
                ('system_migrations_migrated', models.IntegerField(blank=True, null=True, verbose_name='System Migrations (at dump time)')),
                ('dump_migration_files', models.IntegerField(blank=True, null=True, verbose_name='Dump Migration Files')),
                ('created_at', models.DateTimeField()),
                ('consistent_migrations', models.BooleanField(default=False, verbose_name='Consistent Migrations')),
                ('django_backup_utils_version', models.CharField(blank=True, max_length=10, null=True, verbose_name='django-backup-utils version')),
                ('backup_directories', models.TextField(blank=True, null=True)),
            ],
            options={
                'permissions': (('can_restore_backup', 'Can restore backup'),),
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup', models.TextField()),
                ('params', models.TextField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=200)),
                ('module', models.CharField(max_length=200)),
                ('output', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
