# Generated by Django 5.0.6 on 2024-09-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='backup',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='backup_data',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='params',
        ),
        migrations.RemoveField(
            model_name='backup',
            name='size_bytes',
        ),
        migrations.AlterField(
            model_name='backup',
            name='backup_file',
            field=models.FilePathField(path='/home/janni/django-elternsprechtag/backup'),
        ),
    ]
