# Generated by Django 5.0.6 on 2024-09-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0002_remove_backup_backup_remove_backup_backup_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'permissions': (('can_restore_backup', 'Can restore backup'), ('can_add_backup', 'Can create a backup'))},
        ),
        migrations.AddField(
            model_name='backup',
            name='backup_type',
            field=models.CharField(choices=[('A', 'Automatically created backup'), ('M', 'Manually created backup'), ('U', 'User-uploaded backup')], default='M', max_length=1),
        ),
    ]
