# Generated by Django 5.0.6 on 2024-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0003_alter_backup_options_backup_backup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='backup_type',
            field=models.CharField(choices=[('A', 'Automatically created backup'), ('M', 'Manually created backup'), ('U', 'User-uploaded backup')], default='A', max_length=1),
        ),
    ]
