# Generated by Django 5.0.6 on 2024-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0007_backup_keep_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='validation_hash',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
