# Generated by Django 5.0.6 on 2024-09-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0009_backup_external'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backuplog',
            name='backup',
        ),
    ]
