# Generated by Django 5.0.6 on 2024-09-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0010_remove_backuplog_backup'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuplog',
            name='modlue',
            field=models.TextField(null=True),
        ),
    ]
