# Generated by Django 5.0.6 on 2024-09-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0011_backuplog_modlue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backuplog',
            old_name='modlue',
            new_name='module',
        ),
    ]
