# Generated by Django 5.0.6 on 2024-09-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0012_rename_modlue_backuplog_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='external',
            field=models.BooleanField(default=False, help_text='Dies ist eine Angabe darüber, ob das Backup von einem Externen Server stammt oder extern modifiziert wurde.'),
        ),
    ]
