# Generated by Django 5.0.6 on 2024-09-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0013_alter_backup_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='backup_file',
            field=models.FilePathField(path='/home/bastian/django-elternsprechtag/django-elternsprechtag/backup'),
        ),
    ]
