# Generated by Django 5.0.6 on 2024-09-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0016_alter_backup_options_alter_backup_backup_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'permissions': (('can_restore_backup', 'Kann Backup wiederherstellen'), ('can_add_backup', 'Kann Backup erstellen'))},
        ),
    ]
