# Generated by Django 5.0.6 on 2024-09-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0017_alter_backup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='backup_file',
            field=models.FilePathField(path='/home/bastian/django-elternsprechtag/django-elternsprechtag/backup'),
        ),
    ]
