# Generated by Django 5.0.6 on 2024-09-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0018_alter_backup_backup_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='backup_file',
            field=models.FilePathField(path='/home/janni/django-elternsprechtag/backup'),
        ),
    ]
