# Generated by Django 5.0.6 on 2024-09-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0019_alter_backup_backup_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='backup_file',
            field=models.FilePathField(),
        ),
    ]
