# Generated by Django 5.0.6 on 2024-10-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_backup', '0020_alter_backup_backup_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='validation_hash',
            field=models.CharField(max_length=512, null=True, unique=True),
        ),
    ]
