name: Docker Image CI

on:
  workflow_run:
    workflows: ["Django CI", "CodeQL"]
    branches: [development]
    types: 
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          ref: development
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: https://github.com/Janni2006/django-elternsprechtag.git#development
          push: true
          tags: janni06/django-elternsprechtag:dev
